### ISSUE TITLE
Allow updating device IP address

### ISSUE THREAD

**Issue by vilhalmer** [zhbjsh/homeassistant-ssh#12]
I just had to re-ip a device on my network and getting it reconnected to the integration was non-trivial. I tried renaming it to `device-old` so I could create it with the existing device ID and keep all my automations working and still have the sensor config to copy over when recreating it. That resulted in the integration telling me that the device was already configured, presumably since the MAC address was the same. I ended up having to copy out the config into a text file so I could delete the old entry, add the new one, and paste it back in. Being able to just edit the connection parameters of existing devices would make this much easier to deal with. Luckily due to a quirk of home assistant internals, it still kept the old device ID.

This is admittedly an infrequent occurrence, not the end of the world but a very nice-to-have. :)

**Comment by leoravagnani** [comment]
I'm backing this up! I just had to do the same and it's a PITA ): 
One way around it would be setting up a Local DNS name for the device (assuming you've got the means), I did so through my Unifi router. BUT, it seems I put the plain IP address when I first set  this up - can't really tell as the the config is not visible anywhere

**Comment by zhbjsh** [comment]
Hi! Thanks a lot for your feedback! I will take a look into this and if possible add an option to change the connection settings of existing devices in the next version.

**Comment by zhbjsh** [comment]
I added the option to reconfigure devices in version 0.9.6, you can find it by clicking on the three dots in the settings. Hope it works for you!

**Comment by leoravagnani** [comment]
@zhbjsh Just updated and checked the reconfigure page, looks good! thanks!

**Comment by vilhalmer** [comment]
This is awesome, thanks so much!
