### ISSUE TITLE
Where am I wrong?

### ISSUE THREAD

**Issue by ickok1984** [zhbjsh/homeassistant-ssh#14]
hi guys where am I wrong?
![Screenshot 2024-05-30 213206](https://github.com/zhbjsh/homeassistant-ssh/assets/65831778/17ad09c0-3447-45a2-a86d-adf45ef18ca7)

**Comment by zhbjsh** [comment]
Hi! Key file and host keys file should be files, not folders (for example /root/.ssh/id_rsa and /root/.ssh/known_hosts).
