### ISSUE TITLE
Shell access from webUI?

### ISSUE THREAD

**Issue by NonaSuomy** [zhbjsh/homeassistant-ssh#2]
How do you access a shell once you have established the connection like the other addon?
paramiko SSHClient.invoke_shell => https://github.com/tsl0922/ttyd
![image](https://github.com/zhbjsh/homeassistant-ssh/assets/1906575/dd48295c-d4ea-4a19-9ddc-63c9a021102c)

**Comment by zhbjsh** [comment]
Hi! It is not possible to open a terminal from the UI, but you can test single commands and view their outputs in Developer Tools -> Actions -> SSH: Execute Command
