### ISSUE TITLE
Power button does not work for Windows 11 but restart button does.

### ISSUE THREAD

**Issue by vvdiaz** [zhbjsh/homeassistant-ssh#21]
Hi,

Just added a new Windows 11 device entry and the power button does not work, but the restart button works perfectly. As you can see in the attached image the 'Allow to turn off device' checkbox is set but does not work. The restart button works perfectly though. If I open an SSH session to the PC and manually enter the command it will shut it down so is not the PC.

![image](https://github.com/user-attachments/assets/8aae2e65-b172-4906-a558-19401cafbb8e)

**Comment by zhbjsh** [comment]
Hi, thanks a lot for the feedback and sorry for the late reply. The correct command should be `shutdown -s -t 0`, I already fixed it in the new version!

**Comment by vvdiaz** [comment]
> Hi, thanks a lot for the feedback and sorry for the late reply. The correct command should be `shutdown -s -t 0`, I already fixed it in the new version!

Hi, works perfectly now. Thanks!
