### ISSUE TITLE
CPU temperature sensor not working

### ISSUE THREAD

**Issue by Vladd1980** [zhbjsh/homeassistant-ssh#24]
I have an old Dlink 320 NAS and since it does not support SNMP I resorted to SSH integration and I must say that it works great! But after installing it, a large number of sensors were available to me, but there was no processor temperature sensor. This sensor is included in the integration configuration. Through trial and error, I got a command with which I can get temperature data on the command line. it looks like this: cat /tmp/sys/temp1_input. Next, I changed the command in the integration configuration file:
  - command: cat /tmp/sys/temp1_input
  scan_interval: 60
  sensors:
    - type: number
      name: Temperature
      key: temperature
      dynamic: true
      separator: ","
      unit_of_measurement: °C 
But unfortunately there is still no temperature sensor. What am I doing wrong?

**Comment by Vladd1980** [comment]
I found the solution myself! Here is this line: 
 dynamic: true
 was superfluous

**Comment by zhbjsh** [comment]
Great, thanks for the feedback! Yes, `dynamic: true` is not necessary if your command only returns one single temperature value.
