### ISSUE TITLE
Allow returned responses to be optional in actions configuration

### ISSUE THREAD

**Issue by holysoles** [zhbjsh/homeassistant-ssh#26]
I'm working on creating a universal media player entity, which requires me to run a SSH command on a Linux host to set the volume since MPD isn't handling that properly. However, when doing this through an `execute_command` action from this integration, I get an error:

<img width="506" alt="Screenshot 2024-11-11 at 6 00 03 PM" src="https://github.com/user-attachments/assets/3fc4d36f-9331-4031-92ae-b81692fb146b">

This appears to be coming from HA [here](https://github.com/home-assistant/core/blob/dev/homeassistant/core.py#L2755) because the actions/services provided here are set to require responses to be returned. It seems like it would be possible to register actions as `SupportsResponse.OPTIONAL`, and expose a new parameter in the action data for `execute_command` for whether or not a response should be returned (default true for backwards compatibility).

I started looking into implementing this in a PR here but seems like it might also require updates to [ssh-terminal-manager](https://github.com/zhbjsh/ssh-terminal-manager)

**Comment by zhbjsh** [comment]
Thanks for the feedback! I will try to make the response optional when I have time!

**Comment by zhbjsh** [comment]
I made all service responses optional in version 1.0.1, please take a look if everything works!

**Comment by holysoles** [comment]
It works perfectly! Thank you for working on this
