### ISSUE TITLE
Help with command

### ISSUE THREAD

**Issue by wcavanagh** [zhbjsh/homeassistant-ssh#29]
I am trying to log in to a linux device and send the command "miner restart"

I have this code but just get an error failed to execute any ideas?

```
- command: miner restart
  name: Start miner
  icon: mdi:script-text-play
```

If I login using HA terminal, then just type miner restart it works perfect.

**Comment by wcavanagh** [comment]
The SSL seems to connect well, and logs in ok.  However the command just dont seem to be sent well

**Comment by zhbjsh** [comment]
Hi! Did you try to run your command with `ssh.execute_command` action in the developer tools? Could you please post the response you are getting?

**Comment by wcavanagh** [comment]
I have not done that, sorry, how do I do that? sorry still learning, it is now giving me sensor data from the remote device, so we are definitely connected, just unable to send the commands i need :) Thank you for your help again, really close to making this work

**Comment by wcavanagh** [comment]
Sorry still struggling with this.  Can you help with what I type?

So the order I do this manually is.  SSH into the linux machine with username and password.  Then the command I would type is miner stop or miner start followed by enter.  That's all I need.  Not sure how to format this in here.

**Comment by wcavanagh** [comment]
I got it working, and found the issue.  Please close this, I had to send the command like this

echo 1 | sudo -S miner start
