### ISSUE TITLE
Unable to configure on off switch 

### ISSUE THREAD

**Issue by GabrielPearce** [zhbjsh/homeassistant-ssh#3]
trying to configure a switch so that google assistant/homebridge can detect this to turn on and off devices

example of what I have used in the past (not with homeassistant-ssh)

  - platform: wake_on_lan
    name: "example"
    mac: "01:01:01:01:01;01"
    turn_off:
      service: shell_command.turn_off
      
      
     I have been trying to configure this with:
     
       - platform: wake_on_lan
         mac: 18:C0:4D:0D:33:C3
         name: "gabe-pc"
         host: 192.168.1.71
           turn_off:
           service: ssh.run_action
           data:
             key: "turn_off"
      
      However this does not work, please let me know if I am missing something. It would be great if there was a toggle switch for this (off being ssh comand and on being WOL command)

**Comment by zhbjsh** [comment]
Hi! Did you install the SSH integration and successfully added your device? If so, you should be able to turn it on/off either by using the power button or the ssh.turn_on/ssh.turn_off services. Also make sure you enabled "Allow to turn the device off" in the device configuration.
