### ISSUE TITLE
SSH Connection failed

### ISSUE THREAD

**Issue by tompijls** [zhbjsh/homeassistant-ssh#30]
Trying to create a connection with a Key file

I get following warning in the logs: 
`2024-11-19 09:09:16.001 WARNING (MainThread) [custom_components.ssh.config_flow] SSH connection failed ([Errno 2] No such file or directory: 'id_rsa')`

Config
<img width="377" alt="Screenshot 2024-11-19 at 09 07 55" src="https://github.com/user-attachments/assets/74b50492-0d7c-40cb-a5d3-0bfa5eb6d3c7">

id_rsa is definitely present in ~/.ssh 
<img width="776" alt="Screenshot 2024-11-19 at 09 10 28" src="https://github.com/user-attachments/assets/dfc124b6-36a2-482b-b660-9d3c94fd9b6a">

Any suggestions?

**Comment by zhbjsh** [comment]
Hi! Try it first without any key file specified, the integration should load keys inside `~/.ssh` automatically. If not, enter the full path to your file, not just the file name. Hope that works!

**Comment by tompijls** [comment]
Thanks for quick response.

It does work when i fill in username and password.

I tried again using full path, and leaving key file blank, and then i get both errors respectively:
`2024-11-19 10:23:49.380 WARNING (MainThread) [custom_components.ssh.config_flow] SSH connection failed ([Errno 2] No such file or directory: '/config/.ssh/id_rsa')
2024-11-19 10:24:37.710 WARNING (MainThread) [custom_components.ssh.config_flow] SSH connection failed (No authentication methods available)`

**Comment by zhbjsh** [comment]
Yea, `/root/.ssh/id_rsa` doesn't work if you are using Home Assistant OS, but everything inside `/config` should be fine. Are you sure your file is at `/config/.ssh/id_rsa`?

**Comment by tompijls** [comment]
Yes I'm sure.

So when I ssh into my homeassistant (on odroid) I have following structure:

/config which is a link to /homeassistant
/homeassistant
/root

inside homeassistant, there is a .ssh folder, which is a link to /data/.ssh
inside config, there is also a .ssh folder linking to /data/.ssh
inside root there is also a .ssh folder, again linking to /data/.ssh

data has read access, as does .ssh
`drwxr-xr-x    4 root     root          4096 Nov 19 18:52 data`
`drwxr--r--    2 root     root          4096 Nov 19 18:52 .ssh`

Permissions for the keys are:
`-rw-------    1 root     root          2602 Nov 18  2022 id_rsa`
`-rw-r--r--    1 root     root           567 Nov 18  2022 id_rsa.pub`

Errors remain the same:
`2024-11-19 18:55:53.018 WARNING (MainThread) [custom_components.ssh.config_flow] SSH connection failed ([Errno 2] No such file or directory: '/data/.ssh/id_rsa')`

`2024-11-19 18:56:40.642 WARNING (MainThread) [custom_components.ssh.config_flow] SSH connection failed ([Errno 2] No such file or directory: '/homeassistant/.ssh/id_rsa')`

`2024-11-19 19:09:46.666 WARNING (MainThread) [custom_components.ssh.config_flow] SSH connection failed ([Errno 2] No such file or directory: '/config/.ssh/id_rsa')`
