### ISSUE TITLE
 {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by jnuha** [zhbjsh/homeassistant-ssh#31]
Could not add integration because of error Config flow could not be loaded: {"message":"Invalid handler specified"}
![z1](https://github.com/user-attachments/assets/a92ea185-c2c4-4410-9286-1958d0f83114)

Logs Home Assistant
![z2](https://github.com/user-attachments/assets/fedb3b74-4476-410a-a990-57c3995431e8)
![z3](https://github.com/user-attachments/assets/5b1d61dc-a388-4524-bde4-fc4f5af0f462)

Home Assistant Core: 
2024.11.3

**Comment by zhbjsh** [comment]
Hi, thanks for the info. Please update the integration to 1.2.0 and check if the problem is solved!
