### ISSUE TITLE
Sensor unknown when output is 0

### ISSUE THREAD

**Issue by bower9065** [zhbjsh/homeassistant-ssh#5]
Using "apt-get -s -o Debug::NoLocking=true upgrade |grep -c ^Inst" to check for updates on linux vms works unless the output is 0. 
When 0 sensor changes to Unknown. Shows correctly in Putty & console.

**Comment by zhbjsh** [comment]
Hi! Could you please send me your sensor configuration, so I can take a look at it? Thanks!
