### ISSUE TITLE
Host is offline

### ISSUE THREAD

**Issue by WilcoSnel** [zhbjsh/homeassistant-ssh#6]
I can connect to my windows device through the official HASS terminal addon using "ssh username@ip". But using the same details to connect using the ssh addon it keeps saying Host is offline.

**Comment by zhbjsh** [comment]
Hi, sorry for the very slow answer, could you please test if your windows device replies to ping requests?

**Comment by WilcoSnel** [comment]
Wasn't able to ping. Had a look and my network profile was set to private and the option to be "visible on the network" was enabled. Then noticed inbound ICMP firewall rules were still disabled. Enabled these and then worked like a charm.
